[package]
name = "ffi_derive"
version = "0.1.0"
authors = ["Nicholas Smillie <nicholas@agrian.com>"]
repository = "https://github.com/agrian-inc/agrian_types"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
ffi_common = { path = "../ffi_common" }
heck = "0.3"
paste = "1.0"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }

[dev-dependencies]
chrono = "0.4"
uuid = { version = "0.8", features = ["v4"] }
