[package]
name = "ffi_derive"
version = "0.1.0"
authors = ["Nicholas Smillie <nicholas@agrian.com>"]
repository = "https://github.com/agrian-inc/agrian_types"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["full"] }
proc-macro2 = "1.0"
quote = "1.0"
paste = "1.0"
heck = "0.3"
ffi_common = { path = "../ffi_common" }
